# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reglogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=1000)),
                ('tripdesc', models.TextField(max_length=1000)),
                ('startdate', models.DateField()),
                ('returndate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joinpeople', models.ManyToManyField(related_name='joinpeoples', to='app_reglogin.User')),
                ('tripuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripusers', to='app_reglogin.User')),
            ],
        ),
    ]
